version: "3.5"

services:
    redis:
      image: redis:alpine
      container_name: ${PROJECT_NAME}-redis

    postgres:
      image: postgres:9.5-alpine
      container_name: ${PROJECT_NAME}-postgres
      volumes:
        - ./sourcefiles/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        # - SERVICE_TAG=${POSTGRES_USER}
        # - SERVICE_NAME=${POSTGRES_USER}
      ports:
        - "54323:5432"
      # restart: always
      # healthcheck:
      #   test: ["CMD", "pg_isready", "-U", "auth"]
      #   interval: 30s
      #   timeout: 3s
      #   retries: 5
      # networks:
      #   testing_net:
      #     ipv4_address: 0.0.0.0

    nginx:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-nginx
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./sourcefiles/nginx/sites/:/etc/nginx/conf.d/
        - ./sourcefiles/nginx/ssl/:/etc/ssl/
      networks:
        testing_net:
          ipv4_address: 172.28.1.3

    webserver-app-001:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver-app-001
      working_dir: /application/app-001
      build:
        context: application/app-001
        dockerfile: Dockerfile
      depends_on:
        - "nginx"
        - "postgres"
      volumes:
        - ./application/app-001:/application/app-001
      ports:
        - "8080:80"
      # networks:
      #   testing_net:
      #     ipv4_address: 172.28.1.4

    webserver-app-002:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver-app-002
      working_dir: /application/app-002
      volumes:
        - ./application/app-002:/application/app-002
      ports:
        - "8081:80"
      # networks:
      #   testing_net:
      #     ipv4_address: 172.28.1.5

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      ports:
        - "9000:9000"
      networks:
        testing_net:
          ipv4_address: 172.28.1.6
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16